on: push

jobs:
  build-container:
    name: Build container
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN}}
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: duccioo/github-database-telegrambot:raspberrypi, docker pull duccioo/github-database-telegrambot:${{ github.run_number}}
